apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplesite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simplesite
  template:
    metadata:
      labels:
        app: simplesite
    spec:
      containers:
      - name: simplesite
        image: 107995894928.dkr.ecr.us-west-2.amazonaws.com/simplesite:1
        resources:
          requests:
            memory: 50Mi
            cpu: 50m
          limits:
            memory: 200Mi
            cpu: 200m
        ports:
        - containerPort: 80
      


